// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using moa.Data;

#nullable disable

namespace moa.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260126160109_AddPinAndStoreSettings")]
    partial class AddPinAndStoreSettings
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("moa.Models.CardMonthlyBalance", b =>
                {
                    b.Property<int>("CardMonthlyBalanceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CardMonthlyBalanceId"));

                    b.Property<int>("CardId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CloseAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("MembersCountSnapshot")
                        .HasColumnType("int");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("OpenAt")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("OpeningBalance")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("YearMonth")
                        .HasColumnType("int");

                    b.HasKey("CardMonthlyBalanceId");

                    b.HasIndex("CardId", "OpenAt");

                    b.HasIndex("CardId", "YearMonth")
                        .IsUnique();

                    b.ToTable("CardMonthlyBalances");
                });

            modelBuilder.Entity("moa.Models.Customer", b =>
                {
                    b.Property<int>("CustomerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CustomerId"));

                    b.Property<string>("Address")
                        .HasMaxLength(400)
                        .HasColumnType("nvarchar(400)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("NationalId")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Phone")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("CustomerId");

                    b.HasIndex("FullName");

                    b.ToTable("Customers");
                });

            modelBuilder.Entity("moa.Models.CustomerStoreAssignment", b =>
                {
                    b.Property<int>("AssignmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AssignmentId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("EndAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("StartAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("StoreId")
                        .HasColumnType("int");

                    b.HasKey("AssignmentId");

                    b.HasIndex("CustomerId")
                        .IsUnique()
                        .HasFilter("[EndAt] IS NULL");

                    b.HasIndex("StoreId");

                    b.HasIndex("CustomerId", "StartAt");

                    b.ToTable("CustomerStoreAssignments");
                });

            modelBuilder.Entity("moa.Models.Owner", b =>
                {
                    b.Property<int>("OwnerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OwnerId"));

                    b.Property<string>("Address")
                        .HasMaxLength(400)
                        .HasColumnType("nvarchar(400)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("NationalId")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Phone")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("OwnerId");

                    b.ToTable("Owners");
                });

            modelBuilder.Entity("moa.Models.Product", b =>
                {
                    b.Property<int>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProductId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("StoreId")
                        .HasColumnType("int");

                    b.Property<string>("UnitName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("ProductId");

                    b.HasIndex("StoreId");

                    b.HasIndex("StoreId", "ProductName")
                        .IsUnique();

                    b.ToTable("Products");
                });

            modelBuilder.Entity("moa.Models.RationCard", b =>
                {
                    b.Property<int>("CardId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CardId"));

                    b.Property<string>("CardNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int>("MembersCount")
                        .HasColumnType("int");

                    b.Property<byte[]>("PinHash")
                        .HasMaxLength(128)
                        .HasColumnType("varbinary(128)");

                    b.Property<byte[]>("PinSalt")
                        .HasMaxLength(128)
                        .HasColumnType("varbinary(128)");

                    b.HasKey("CardId");

                    b.HasIndex("CardNumber")
                        .IsUnique();

                    b.HasIndex("CustomerId")
                        .IsUnique();

                    b.ToTable("RationCards");
                });

            modelBuilder.Entity("moa.Models.Store", b =>
                {
                    b.Property<int>("StoreId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StoreId"));

                    b.Property<string>("Address")
                        .HasMaxLength(400)
                        .HasColumnType("nvarchar(400)");

                    b.Property<string>("CommercialRegNo")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int>("OwnerId")
                        .HasColumnType("int");

                    b.Property<string>("Phone")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("StoreName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("StoreId");

                    b.HasIndex("OwnerId");

                    b.ToTable("Stores");
                });

            modelBuilder.Entity("moa.Models.StoreProductMonthlyPrice", b =>
                {
                    b.Property<int>("StoreProductMonthlyPriceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StoreProductMonthlyPriceId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("StoreId")
                        .HasColumnType("int");

                    b.Property<decimal>("UnitPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("YearMonth")
                        .HasColumnType("int");

                    b.HasKey("StoreProductMonthlyPriceId");

                    b.HasIndex("ProductId");

                    b.HasIndex("StoreId", "YearMonth");

                    b.HasIndex("StoreId", "ProductId", "YearMonth")
                        .IsUnique();

                    b.ToTable("StoreProductMonthlyPrices");
                });

            modelBuilder.Entity("moa.Models.StoreSetting", b =>
                {
                    b.Property<int>("StoreId")
                        .HasColumnType("int");

                    b.Property<bool>("AllowEarlyOpenNextMonth")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("NearEmptyThresholdAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("StoreId");

                    b.ToTable("StoreSettings");
                });

            modelBuilder.Entity("moa.Models.WithdrawalAllocation", b =>
                {
                    b.Property<int>("AllocationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AllocationId"));

                    b.Property<decimal>("AllocatedAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("CardMonthlyBalanceId")
                        .HasColumnType("int");

                    b.Property<int>("ReceiptId")
                        .HasColumnType("int");

                    b.HasKey("AllocationId");

                    b.HasIndex("CardMonthlyBalanceId");

                    b.HasIndex("ReceiptId");

                    b.HasIndex("ReceiptId", "CardMonthlyBalanceId")
                        .IsUnique();

                    b.ToTable("WithdrawalAllocations");
                });

            modelBuilder.Entity("moa.Models.WithdrawalAllocationItem", b =>
                {
                    b.Property<int>("AllocationItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AllocationItemId"));

                    b.Property<int>("AllocationId")
                        .HasColumnType("int");

                    b.Property<decimal>("LineTotal")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasComputedColumnSql("ROUND([Quantity] * [UnitPrice], 2)", true);

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<decimal>("Quantity")
                        .HasPrecision(18, 3)
                        .HasColumnType("decimal(18,3)");

                    b.Property<decimal>("UnitPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("AllocationItemId");

                    b.HasIndex("AllocationId");

                    b.HasIndex("ProductId");

                    b.ToTable("WithdrawalAllocationItems");
                });

            modelBuilder.Entity("moa.Models.WithdrawalReceipt", b =>
                {
                    b.Property<int>("ReceiptId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ReceiptId"));

                    b.Property<int>("CardId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("StoreId")
                        .HasColumnType("int");

                    b.Property<decimal>("TotalAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("WithdrawnAt")
                        .HasColumnType("datetime2");

                    b.HasKey("ReceiptId");

                    b.HasIndex("CardId", "WithdrawnAt");

                    b.HasIndex("StoreId", "WithdrawnAt");

                    b.ToTable("WithdrawalReceipts");
                });

            modelBuilder.Entity("moa.Models.WithdrawalReceiptItem", b =>
                {
                    b.Property<int>("ReceiptItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ReceiptItemId"));

                    b.Property<decimal>("LineTotal")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasComputedColumnSql("ROUND([Quantity] * COALESCE([UnitPrice], 0), 2)", true);

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<decimal>("Quantity")
                        .HasPrecision(18, 3)
                        .HasColumnType("decimal(18,3)");

                    b.Property<int>("ReceiptId")
                        .HasColumnType("int");

                    b.Property<decimal?>("UnitPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("ReceiptItemId");

                    b.HasIndex("ProductId");

                    b.HasIndex("ReceiptId", "ProductId")
                        .IsUnique();

                    b.ToTable("WithdrawalReceiptItems");
                });

            modelBuilder.Entity("moa.Models.CardMonthlyBalance", b =>
                {
                    b.HasOne("moa.Models.RationCard", "Card")
                        .WithMany("MonthlyBalances")
                        .HasForeignKey("CardId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Card");
                });

            modelBuilder.Entity("moa.Models.CustomerStoreAssignment", b =>
                {
                    b.HasOne("moa.Models.Customer", "Customer")
                        .WithMany("StoreAssignments")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("moa.Models.Store", "Store")
                        .WithMany("CustomerAssignments")
                        .HasForeignKey("StoreId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Customer");

                    b.Navigation("Store");
                });

            modelBuilder.Entity("moa.Models.Product", b =>
                {
                    b.HasOne("moa.Models.Store", "Store")
                        .WithMany("Products")
                        .HasForeignKey("StoreId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Store");
                });

            modelBuilder.Entity("moa.Models.RationCard", b =>
                {
                    b.HasOne("moa.Models.Customer", "Customer")
                        .WithOne("RationCard")
                        .HasForeignKey("moa.Models.RationCard", "CustomerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("moa.Models.Store", b =>
                {
                    b.HasOne("moa.Models.Owner", "Owner")
                        .WithMany("Stores")
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("moa.Models.StoreProductMonthlyPrice", b =>
                {
                    b.HasOne("moa.Models.Product", "Product")
                        .WithMany("MonthlyPrices")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("moa.Models.Store", "Store")
                        .WithMany("MonthlyPrices")
                        .HasForeignKey("StoreId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("Store");
                });

            modelBuilder.Entity("moa.Models.StoreSetting", b =>
                {
                    b.HasOne("moa.Models.Store", "Store")
                        .WithOne("StoreSetting")
                        .HasForeignKey("moa.Models.StoreSetting", "StoreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Store");
                });

            modelBuilder.Entity("moa.Models.WithdrawalAllocation", b =>
                {
                    b.HasOne("moa.Models.CardMonthlyBalance", "CardMonthlyBalance")
                        .WithMany("WithdrawalAllocations")
                        .HasForeignKey("CardMonthlyBalanceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("moa.Models.WithdrawalReceipt", "Receipt")
                        .WithMany("Allocations")
                        .HasForeignKey("ReceiptId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CardMonthlyBalance");

                    b.Navigation("Receipt");
                });

            modelBuilder.Entity("moa.Models.WithdrawalAllocationItem", b =>
                {
                    b.HasOne("moa.Models.WithdrawalAllocation", "WithdrawalAllocation")
                        .WithMany("Items")
                        .HasForeignKey("AllocationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("moa.Models.Product", "Product")
                        .WithMany("AllocationItems")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("WithdrawalAllocation");
                });

            modelBuilder.Entity("moa.Models.WithdrawalReceipt", b =>
                {
                    b.HasOne("moa.Models.RationCard", "Card")
                        .WithMany("WithdrawalReceipts")
                        .HasForeignKey("CardId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("moa.Models.Store", "Store")
                        .WithMany("WithdrawalReceipts")
                        .HasForeignKey("StoreId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Card");

                    b.Navigation("Store");
                });

            modelBuilder.Entity("moa.Models.WithdrawalReceiptItem", b =>
                {
                    b.HasOne("moa.Models.Product", "Product")
                        .WithMany("ReceiptItems")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("moa.Models.WithdrawalReceipt", "Receipt")
                        .WithMany("Items")
                        .HasForeignKey("ReceiptId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("Receipt");
                });

            modelBuilder.Entity("moa.Models.CardMonthlyBalance", b =>
                {
                    b.Navigation("WithdrawalAllocations");
                });

            modelBuilder.Entity("moa.Models.Customer", b =>
                {
                    b.Navigation("RationCard");

                    b.Navigation("StoreAssignments");
                });

            modelBuilder.Entity("moa.Models.Owner", b =>
                {
                    b.Navigation("Stores");
                });

            modelBuilder.Entity("moa.Models.Product", b =>
                {
                    b.Navigation("AllocationItems");

                    b.Navigation("MonthlyPrices");

                    b.Navigation("ReceiptItems");
                });

            modelBuilder.Entity("moa.Models.RationCard", b =>
                {
                    b.Navigation("MonthlyBalances");

                    b.Navigation("WithdrawalReceipts");
                });

            modelBuilder.Entity("moa.Models.Store", b =>
                {
                    b.Navigation("CustomerAssignments");

                    b.Navigation("MonthlyPrices");

                    b.Navigation("Products");

                    b.Navigation("StoreSetting");

                    b.Navigation("WithdrawalReceipts");
                });

            modelBuilder.Entity("moa.Models.WithdrawalAllocation", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("moa.Models.WithdrawalReceipt", b =>
                {
                    b.Navigation("Allocations");

                    b.Navigation("Items");
                });
#pragma warning restore 612, 618
        }
    }
}
